<div class="panel-body">
  <?php
  $values = [
    'name' => $view_user->name,
    'email' => $view_user->email,
    'username' => $view_user->username
  ];
  Form::open('editarusuario', $values, [
    'action' => BASE . 'perfil/editar/',
    'prevent' => [
      'focus'
    ]
  ]);

  Form::Textbox(
    'Nome:',
    'name',
    array(
      'required' => 1
    )
  );

  Form::Email(
    'E-mail:',
    'email',
    array(
      'required' => 1
    )
  );

  Form::Textbox(
    'Login:',
    'username',
    array(
      'required' => 1
    )
  );

  Form::Password(
    'Senha',
    'password',
    array(
      'placeholder' => 'Preencha somente se quiser atualizar a senha'
    )
  );

  Form::Button('Atualizar perfil', 'submit', [
    'style' => 'width: 100%',
    'class' => 'btn-success'
  ]);

  Form::close(false);
  ?>
</div>