<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-custom">
      <div class="panel-heading">
        <a id="logo" href="<?php echo BASE; ?>">
          <img class="img-responsive" src="<?php echo IMG; ?>hxphp-logo.png" alt="">
        </a> <br>
        <?php echo (isset($this->menu) ? $this->menu : ''); ?>
      </div>
      <div class="panel-body">
        <?php echo (isset($this->alert) ? $this->alert : ''); ?>
        <form class="form-horizontal" method="POST" action="<?php echo BASE; ?>recuperar/solicitar/">
          <div class="form-group">
            <label for="email" class="col-sm-3 control-label">E-mail:</label>
            <div class="col-sm-8">
              <input type="email" class="form-control" id="email" name="email" placeholder="Forneça seu e-mail" value="<?php echo $this->request->post('email'); ?>">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-3 col-sm-8">
              <button type="submit" class="btn btn-success">Enviar link de redefinição</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
